language: go
sudo: false
os:
  - linux
  - osx
dist: trusty
go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - make

notifications:
  email:
    on_success: never
