language: go

sudo: false

go:
  - "1.11.x"
  - "1.12.x"
  - tip

env:
  - GO111MODULE=on

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go test

notifications:
  email:
    on_success: never
